# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative 'config/application'
require 'pact/tasks'
require 'pact_broker/client/tasks'

Rails.application.load_tasks

PactBroker::Client::PublicationTask.new do | task |
  task.consumer_version = "1.0.1"
  task.pattern = 'spec/pacts/*.json' # optional, default value is 'spec/pacts/*.json'
  task.pact_broker_base_url = "http://localhost"
  # task.tag_with_git_branch = true
  task.tags = ["dev"]
end